:global:
  componentName: MariaDB MaxScale
  githubUrl: https://github.com/projectsyn/component-maxscale
  testMatrix:
    key: instance
    entries:
      - defaults
      - no_container_limits
      - affinity

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
Makefile:
  includes:
    - Makefile.additional.mk
