:global:
  componentName: maxscale
  githubUrl: https://github.com/projectsyn/component-maxscale

docs/antora.yml:
  name: maxscale
  title: MariaDB MaxScale

.github/workflows/test.yaml:
  makeTarget: test -e instance=${{ matrix.instance }}
  matrix:
    key: instance
    entries:
      - defaults
      - no_container_limits

Makefile:
  includes:
    - Makefile.additional.mk
