= Maxscale Parameters

The parent key for the following parameters is `maxscale` and they affect MaxScale itself:

== `namespace`

[horizontal]
type:: string
default:: `syn-maxscale`

The namespace in which to deploy this component.

== `replicas`

[horizontal]
type:: integer
default:: `2`

How many replicas the deployment has.

== `master_only_listen_address`

[horizontal]
type:: string
default:: `0.0.0.0`

== `read_write_listen_address`

[horizontal]
type:: string
default:: `0.0.0.0`

== `db1_address`

[horizontal]
type:: string
default:: `db1.mygalera.example.org`

== `db1_port`

[horizontal]
type:: string
default:: `3306`

== `db2_address`

[horizontal]
type:: string
default:: `db2.mygalera.example.org`

== `db2_port`

[horizontal]
type:: string
default:: `3306`

== `db3_address`

[horizontal]
type:: string
default:: `db3.mygalera.example.org`

== `db3_port`

[horizontal]
type:: string
default:: `3306`

== `service_user`

[horizontal]
type:: string
default:: `maxscale`

== `monitor_user`

[horizontal]
type:: string
default:: `maxscale`

== `service_pwd`

[horizontal]
type:: string
default:: `?{vaultkv:${cluster:tenant}/${cluster:name}/maxscale/service_pwd}`

== `monitor_pwd`

[horizontal]
type:: string
default:: `?{vaultkv:${cluster:tenant}/${cluster:name}/maxscale/monitor_pwd}`

= Pod Affinity Parameters

By default, `affinity` is set to `{}` so the pods get no specific affinity. You can override this freely to [choose any pod affinity rules](https://kubernetes.io/docs/concepts/scheduling-eviction/assign-pod-node/).

[horizontal]
type:: hash
default:: `{}`

```yaml
parameters:
  maxscale:
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: node-role.kubernetes.io/controlplane
              operator: In
              values:
              - "false"
```

= Container Resource Parameters

By default there are no resource limits. As soon as you set *any* of these reource parameters, all the other ones are set to their defaults and you'll have to override them to change them. This prevents generating an invalid manifest.


== `resources.requests.cpu`

[horizontal]
type:: string
default:: `1000m`

== `resources.requests.memory`

[horizontal]
type:: string
default:: `128Mi`

== `resources.limits.cpu`

[horizontal]
type:: string
default:: `2000m`

== `resources.limits.memory`

[horizontal]
type:: string
default:: `512Mi`


== Example

[source,yaml]
----
namespace: example-namespace
maxscale:
  db1_address: db5.othergalera.example.org
  db1_port: 3309
  db2_address: db6.othergalera.example.org
  db2_port: 3307
  db3_address: db7.othergalera.example.org
  db3_port: 3305
  monitor_user: mymonitoruser
  service_user: myserviceuser
  resources:
    requests:
      cpu: 1000m
      memory: 128Mi
    limits:
      cpu: 2000m
      memory: 512Mi
----
